services:
    celsius3_ticket.ticket_manager:
        class: Celsius3\TicketBundle\Manager\TicketManager
        arguments:
           - "@doctrine.orm.entity_manager"
    celsius3_ticket.ticket_helper:
            class: Celsius3\TicketBundle\Helper\TicketHelper
            arguments:
               - "@doctrine.orm.entity_manager"

    app.twig.extension:
             class: Celsius3\TicketBundle\Twig\AppExtension
             public: false
             arguments:
                - "@doctrine.orm.entity_manager"
                - "@router"
                - "@kernel"
             tags:
                 - { name: twig.extension }
