celsius3_notification:
    web_socket_server:
        port: "%notification_port%"        #The port the socket server will listen on
        host: "%notification_host%"   #(optional) The host ip to bind to
        zmq_port: "%notification_zmq_port%"
        zmq_host: "%notification_zmq_host%"