fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        formats:
            json : true
#        templating_formats:
#            html: true
#        force_redirects:
#            html: true
        failed_validation: HTTP_BAD_REQUEST
#        default_engine: twig
    routing_loader: false