framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
#        handler_id: snc_redis.session
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    default_locale: es
    translator: { fallback: es }
#    router:
#        resource: "%kernel.project_dir%/config/routes.yaml"
#        strict_requirements: "%kernel.debug%"
    form: true
    validation: { enable_annotations: true }
#    templating: { engines: [ 'twig' ] } #assets_version: SomeVersionScheme
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        packages:
            administration:
                version: "%assets_version_administration%"
            admin_order:
                version: "%assets_version_admin_order%"
            admin_base_user:
                version: "%assets_version_admin_base_user%"
            admin_institution:
                version: "%assets_version_admin_institution%"
            user:
                version: "%assets_version_user%"
            celsius3:
                version: "%assets_version_celsius3%"
