jms_translation:
    configs:
        app:
            dirs: ["%kernel.project_dir%/public", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/src/Celsius3/CoreBundle/Resources/translations"
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            extractors: [jms_i18n_routing]