#jms_serializer:
#    metadata:
#        directories:
#            FOSUserBundle:
#                namespace_prefix: FOS\UserBundle
#                path: "/config/serializer/fos"
#            FOSMessageBundle:
#                namespace_prefix: FOS\MessageBundle
#                path: "/config/serializer/fos"
#            Celsius3CoreBundle:
#                namespace_prefix: Celsius3
#                path: "/config/serializer/core"
#            Celsius3MessageBundle:
#                namespace_prefix: Celsius3\MessageBundle
#                path: "/config/serializer/message"