snc_redis:
    clients:

# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
# how to configure the bundle.
#
#        default:
#            type: phpredis
#            alias: default
#            dsn: "%env(REDIS_URL)%"

        default:
            type: predis
            alias: default
            dsn: redis://localhost
        session:
            type: predis
            alias: session
            dsn: redis://localhost
        cache:
            type: predis
            alias: cache
            dsn: redis://localhost

    session:
        client: session

    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default          # the name of your entity_manager connection
        result_cache:
            client: cache
            entity_manager: default
        query_cache:
            client: cache
            entity_manager: default