twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        notification_public_url: "%notification_public_url%"
        notification_port: "%notification_port%"
        notification_limit: "%notification_limit%"
        instance_helper: Celsius3\Helper\InstanceHelper
    form_themes:
        - 'Form/fields.html.twig'