name: celsius3_sym5

services:

    apache:
        build: docker/apache/
        ports: [ "80:80" ]
        volumes:
            - .:/var/www/html
        networks:
            - backend
            - frontend
        depends_on:
            - php

    php:
        build:
            context: docker/php/
            args:
                - USERID=1000
                - USERNAME=root
        ports: [ "9000:9000" ]
        volumes:
            - .:/var/www/html
            - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - backend
        depends_on:
            - bd
            - elasticsearch
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - .env.local
        environment:
            PHP_IDE_CONFIG: "serverName=celsius3.istec.org"  # Ajusta según tu configuración
            XDEBUG_MODE: "develop,debug"
            XDEBUG_CONFIG:
                client_host=host.docker.internal
                start_with_request=yes
        entrypoint: [
            "/bin/sh", 
            "-c", 
            "mkdir -p /var/www/html/public/orders && chown www-data:www-data /var/www/html/public/orders && docker-php-entrypoint php-fpm"
        ]

    bd:
        build: docker/bd/
        ports: [ "3306:3306" ]
        volumes:
            - bd:/var/lib/mysql
            - ./docker/bd:/docker-entrypoint-initdb.d
            - ./:/home/node/app
        networks:
            - backend

    node:
        build: docker/node/
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        command: sh -c "npm install && npm run watch"

    elasticsearch:
        build: docker/elasticsearch/
        ports: [ "9200:9200" ]
        networks:
            - backend
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data

    phpmyadmin:
        build: docker/phpmyadmin/
        ports: [ "81:80" ]
        depends_on:
            - bd
        networks:
            - backend

    mailer:
        build: docker/mailer/
        ports:
            - 1080:1080
            - 1025:1025
        networks:
            - backend

networks:
    backend: ~
    frontend: ~

volumes:
    bd: ~
    elasticsearch: ~
