name: "celsius3_sym5"

services:

    apache:
        build: docker/apache/
        ports: [ "80:80" ]
        volumes:
            - .:/var/www/html
        networks:
            - backend
            - frontend
        depends_on:
            - php

    php:
        build:
            context: docker/php/
            args:
                - USERID=1000
                - USERNAME=root
        volumes:
            - .:/var/www/html
        networks:
            - backend
        depends_on:
            - bd
            - elasticsearch

    bd:
        build: docker/bd/
        volumes:
            - bd:/var/lib/mysql
            - ./docker/bd:/docker-entrypoint-initdb.d
        networks:
            - backend

    node:
        build: docker/node/
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        command: sh -c "npm install && npm run watch"

    elasticsearch:
        build: docker/elasticsearch/
        ports: [ "9200:9200" ]
        networks:
            - backend
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data

    phpmyadmin:
        build: docker/phpmyadmin/
        ports: [ "81:80" ]
        depends_on:
            - bd
        networks:
            - backend

    mailer:
        build: docker/mailer/
        ports: [ "1025", "1080" ]

networks:
    backend: ~
    frontend: ~

volumes:
    bd: ~
    elasticsearch: ~
