superadmin_user:
    path: /superadmin/user
    defaults: { _controller: Celsius3\Controller\Superadmin\BaseUser\ListAllUsersViewController }
    methods: [ GET ]

superadmin_user_new:
    path: /superadmin/user/new
    defaults: { _controller: Celsius3\Controller\Superadmin\BaseUser\NewUserViewController }
    methods: [ GET ]