directory_homepage:
    path:   /
    host:   celsius3.prebi.unlp.edu.ar
    defaults: { _controller: Celsius3CoreBundle:Directory:index }

directory_instances:
    path:   /instances
    host:   celsius3.prebi.unlp.edu.ar
    defaults: { _controller: Celsius3CoreBundle:Directory:instances }

directory_statistics:
    path:   /statistics
    host:   celsius3.prebi.unlp.edu.ar
    defaults: { _controller: Celsius3CoreBundle:Directory:statistics }
    options:
        expose: true