fos_user_security_login:
    path: /public/login
    methods: [ GET, POST ]
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path: /public/login_check
    methods: [ POST ]
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path: /user/logout
    methods: [ GET ]
    defaults: { _controller: FOSUserBundle:Security:logout }
