admin_user:
    path: /
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\BaseUser\ListUsersViewController }
    methods: [ GET ]

admin_user_show:
    path: /{id}/show
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\BaseUser\ShowUserViewController }
    methods: [ GET ]
    options:
        expose: true

admin_user_new:
    path: /new
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\BaseUser\NewUserViewController }
    methods: [ GET ]

admin_user_create:
    path: /create
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\BaseUser\CreateUserPostController }
    methods: [ POST ] # No debe retornar html

admin_user_edit:
    path: /{id}/edit
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\BaseUser\EditUserViewController }
    methods: [ GET ]
    options:
        expose: true

admin_user_update:
    path: /{id}/update
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\BaseUser\UpdateUserPostController }
    methods: [ POST ]

admin_user_transform:
    path: /{id}/transform
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\BaseUser\TransformUserViewController }
    methods: [ GET, POST ] # Se debe separar en dos controladores

admin_user_enable:
    path: /{id}/enable
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\BaseUser\EnableUserPutController }
    # methods: [ PUT ] # Hay que modificar las solicitudes con este método
    options:
        expose: true

admin_user_batch:
    path: /batch

admin_user_doUnion:
    path: /batch/doUnion
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\BaseUser\DoUnionPostController }
    methods: [ POST ]

switch_user:
    path: /switch-user
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\BaseUser\SwitchUserPutController }
#    methods: [ PUT ] # Hay que modificar las solicitudes con este método


