admin_rest_events:
    path: /{request_id}
    defaults: { _controller: \Celsius3\CoreBundle\Controller\Admin\Event\AllRequestEventsGetController }
    methods: [ GET ]
    options:
        expose: true

admin_rest_event:
    path: /{request_id}/{event}
    defaults: { _controller: \Celsius3\CoreBundle\Controller\Admin\Event\RequestEventsByTypeGetController }
    methods: [ GET ]
    options:
        expose: true

admin_rest_event_get:
    path: /{id}/get
    defaults: { _controller: \Celsius3\CoreBundle\Controller\Admin\Event\EventGetController }
    methods: [ GET ]
    options:
        expose: true

admin_rest_event_update_observations:
    path: /update_observations/{id}
    defaults: { _controller: \Celsius3\CoreBundle\Controller\Admin\Event\UpdateEventObservationsPostController }
    methods: [ POST ]
    options:
        expose: true

admin_rest_order_event_undo:
    path: /{request_id}/undo
    defaults: { _controller: \Celsius3\CoreBundle\Controller\Admin\Event\CreateUndoEventPostController }
    methods: [ POST ]
    options:
        expose: true

admin_rest_order_request_event:
    path: /{request_id}/request
    defaults: { _controller: \Celsius3\CoreBundle\Controller\Admin\Event\CreateRequestEventPostController }
    methods: [ POST ]
    options:
        expose: true

admin_rest_order_event:
    path: /{request_id}/{event}
    defaults: { _controller: \Celsius3\CoreBundle\Controller\Admin\Event\CreateEventPostController }
    methods: [ POST ]
    options:
        expose: true