directory_homepage:
    path:   /
    host:   directory.localhost
    defaults: { _controller: Celsius3\Controller\DirectoryController::index }

directory_instances:
    path:   /instances
    host:   directory.localhost
    defaults: { _controller: Celsius3\Controller\DirectoryController::instances }

directory_statistics:
    path:   /statistics
    host:   directory.localhost
    defaults: { _controller: Celsius3\Controller\DirectoryController::statistics }
    options:
        expose: true