doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: service
            id: Doctrine\Common\Cache\RedisCache
        query_cache_driver:
            type: service
            id: Doctrine\Common\Cache\RedisCache
        result_cache_driver:
            type: service
            id: Doctrine\Common\Cache\RedisCache

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
