FROM mariadb:12.0.1-ubi9-rc

# Variables de entorno para creación automática de usuario y base
ENV MARIADB_ROOT_PASSWORD=root_pass
ENV MARIADB_DATABASE=celsius3
ENV MARIADB_USER=celsius3_usr
ENV MARIADB_PASSWORD=celsius3_pass

# Exponer el puerto de MariaDB (3306 es el correcto)
EXPOSE 3306
