# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }


directory_homepage:
    path:   /
    host:   celsius3.prebi.unlp.edu.ar
    defaults: { _controller: Celsius3\CoreBundle\Controller\DirectoryController::indexAction }

directory_instances:
    path:   /instances
    host:   celsius3.prebi.unlp.edu.ar
    defaults: { _controller: Celsius3\CoreBundle\Controller\DirectoryController::instancesAction }

directory_statistics:
    path:   /statistics
    host:   celsius3.prebi.unlp.edu.ar
    defaults: { _controller: Celsius3\CoreBundle\Controller\DirectoryController::statisticsAction }
    options:
        expose: true

blog_show:
    path:      /
    defaults:  { _controller: Celsius3\CoreBundle\Controller\PublicController::indexAction }