# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

# logout:
#     path: /logout
#     methods: GET

blog_show:
    path:      /
    defaults:  { _controller: Celsius3\Controller\PublicController::index }