# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

logout:
    path: /auth/logout
    methods: GET

blog_show:
    path:      /
    defaults:  { _controller: Celsius3\Controller\PublicController::index }

Celsius3:
    resource: '../src/Controller/'
    type: annotation
    prefix: '/{_locale}'
    requirements:
        _locale: en|es|pt
    defaults:
        _locale: es