admin_instance_data_request:
    path: /orders
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\DataRequest\NewOrdersDataRequestViewController }
    methods: [ GET, POST ]
    options:
        expose: true

admin_instance_users_data_request:
    path: /users
    defaults: { _controller: Celsius3\CoreBundle\Controller\Admin\DataRequest\NewUsersDataRequestViewController }
    methods: [ GET, POST ]
    options:
        expose: true