<?php

namespace Celsius\Celsius3Bundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BaseUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseUserRepository extends DocumentRepository
{

    public function findByTerm($term, $instance = null, $in = array(), $limit = null, $librarian = null)
    {
        $expr = new \MongoRegex('/.*' . $term . '.*/i');

        $qb = $this->createQueryBuilder();
        $qb = $qb->addOr($qb->expr()->field('name')->equals($expr))
                ->addOr($qb->expr()->field('surname')->equals($expr))
                ->addOr($qb->expr()->field('username')->equals($expr));

        if (!is_null($instance))
            $qb = $qb->field('instance.id')->equals($instance->getId());
        
        if (!is_null($librarian))
            $qb = $qb->field('librarian.id')->equals($librarian->getId());

        if (!is_null($limit))
            $qb = $qb->limit(10);

        return $qb->getQuery();
    }

}