<?php

namespace Celsius\Celsius3Bundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends DocumentRepository
{

}