<?php

namespace Celsius\Celsius3Bundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends DocumentRepository
{

    public function findByTerm($term, $instance = null, $in = array(), $limit = null, $librarian = null)
    {
        $qb = $this->createQueryBuilder();

        if (!empty($in))
        {
            $secondary = array();
            foreach ($in as $repository => $term)
            {
                $secondary = array_keys($this->getDocumentManager()
                                ->getRepository('CelsiusCelsius3Bundle:' . $repository)
                                ->findByTerm($term, $instance)
                                ->execute()
                                ->toArray());
            }

            $qb = $qb->field('owner.id')->in($secondary);
        } else
        {

            $expr = new \MongoRegex('/.*' . $term . '.*/i');

            $qb = $qb->addOr($qb->expr()->field('comments')->equals($expr))
                    ->addOr($qb->expr()->field('code')->equals(intval($term)))
                    ->addOr($qb->expr()->field('materialData.title')->equals($expr))
                    ->addOr($qb->expr()->field('materialData.authors')->equals($expr))
                    ->addOr($qb->expr()->field('materialData.year')->equals($expr));
        }

        if (!is_null($instance))
            $qb = $qb->field('instance.id')->equals($instance->getId());
        
        if (!is_null($librarian))
            $qb = $qb->field('librarian.id')->equals($librarian->getId());

        if (!is_null($limit))
            $qb = $qb->limit(10);

        return $qb->getQuery();
    }

}