<?php

namespace Celsius3\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Celsius3\CoreBundle\Manager\InstanceManager;

/**
 * InstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanceRepository extends DocumentRepository
{

    public function findAllExceptDirectory()
    {
        return $this->createQueryBuilder()
                        ->field('url')->notEqual(InstanceManager::INSTANCE__DIRECTORY);
    }

}
