<?php

/*
 * Celsius3 - Order management
 * Copyright (C) 2014 PrEBi <info@prebi.unlp.edu.ar>
 *
 * This file is part of Celsius3.
 *
 * Celsius3 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Celsius3 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Celsius3.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Celsius3\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Celsius3\CoreBundle\Entity\BaseUser;
use Celsius3\CoreBundle\Entity\Instance;
use Celsius3\CoreBundle\Manager\StateManager;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends EntityRepository
{

    public function findByTerm($term, Instance $instance = null)
    {
        $qb = $this->createQueryBuilder('j');

        $qb = $qb->orWhere($qb->expr()->like('j.name', $qb->expr()->literal('%' . $term . '%')))
                ->orWhere($qb->expr()->like('j.abbreviation', $qb->expr()->literal('%' . $term . '%')))
                ->orWhere($qb->expr()->like('j.responsible', $qb->expr()->literal('%' . $term . '%')))
                ->orWhere($qb->expr()->like('j.ISSN', $qb->expr()->literal('%' . $term . '%')))
                ->orWhere($qb->expr()->like('j.ISSNE', $qb->expr()->literal('%' . $term . '%')));

        $directory = $this->getEntityManager()->getRepository('Celsius3CoreBundle:Instance')
                ->findOneBy(array(
            'url' => \Celsius3\CoreBundle\Manager\InstanceManager::INSTANCE__DIRECTORY,
        ));

        if (!is_null($instance)) {
            $qb = $qb->andWhere('j.instance = :instance_id OR j.instance = :directory_id')
                    ->setParameter('instance_id', $instance->getId())
                    ->setParameter('directory_id', $directory->getId());
        }

        return $qb->getQuery();
    }
}
